apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: autoscale-demo
  labels: { app: nginx }
spec:
  replicas: 2
  selector:
    matchLabels: { app: nginx }
  template:
    metadata:
      labels: { app: nginx }
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "250m", memory: "128Mi" }
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: nginx-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: autoscale-demo
data:
  index.html: |
    <!doctype html>
    <html><head><title>NGINX HPA Demo</title></head>
    <body>
      <h1>NGINX + HPA</h1>
      <p>Página estática para testes. Gere carga para observar métricas.</p>
    </body></html>
